name: "[CD] Continuous Delivery"
# Every time there's a commit or a pull request is opened:

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Debug"
        run: "ls -la"
      - name: "Install dependencies"
        run: "npm install"
      - name: "lint"
        run: npx vercel --prod
